spring:
  thymeleaf:
  prefix: classpath:/templates/
  suffix: .html

  datasource:
    url: jdbc:mysql://database-1.ckvoxrdychzo.ap-northeast-2.rds.amazonaws.com:3306/demo?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: gjspark513
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
# org.hibernate.type: trace
